name: CI

on:
  push:
    branches:
      - master  # Change to 'master' since you use this branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Build the Docker image
        run: |
          docker build -t simple-python-app:latest .

      - name: Run tests inside the Docker container
        run: |
          docker run simple-python-app:latest

      - name: Log in to Docker Hub
        if: success()  # Only log in if the tests are successful
        run: |
         echo "qmobilee2" | docker login -u 78017801 --password-stdin

      - name: Tag Docker image
        if: success()  # Only tag the image if the tests are successful
        run: |
          docker tag simple-python-app:latest 78017801/python_test

      - name: Push Docker image to Docker Hub
        if: success()  # Only push the image if the tests are successful
        run: |
         docker push 78017801/python_test:latest
